### ISSUE TITLE
Duplicate name in Yang model

### ISSUE THREAD

**Issue by wangqilei** [Open-Network-Models-and-Interfaces-ONMI/TAPI#382]
During implementation, we found that there are a number of duplicate name in the yang model, for example, there are two "rule" in the below list:
    list rule {
            key 'local-id';
            min-elements 1;
            uses rule;
            description "none";
     }
Usually, the yang compile tools would treat this as illeague. I'm not sure whether it's caused by UML-YANG tools or something else. Could we fix that?

Thanks
Qilei

**Comment by amazzini** [comment]
This issue has been closed due to the lack of activity for more than one year.
Please reopen it if follow up is necessary.
