### ISSUE TITLE
ITU-T G.709 ODU PM delay measurement (DMp)

### ISSUE THREAD

**Issue by amazzini** [Open-Network-Models-and-Interfaces-ONMI/TAPI#450]
TAPI ODU MEP (OduMepPac) includes the attributes necessary for triggering On Demand Delay Measurement (dmSource and dmValue, applicable only on ODU Trail Termination and Tandem Connection Termination), but the delay counter, result of this measurement, seems missing. It appears missing also in current ITU-T G.874 and G.875.
It is suggested to check:
1) whether currently defined dmSource and dmValue attributes are appropriate in the light of TAPI network view,
2) add the delay counter (likely) to OduPmPac, evaluating the introduction of ODU Current/History Data etc.

**Comment by bzeuner** [comment]
According to my understanding, the dmValue is not relevant for management. A function that toggles the value is enough.

**Comment by amazzini** [comment]
The apparently missing delay counter is defined in G.798:
14.2.1.2	**ODUP trail termination sink function (ODUP_TT_Sk)**
14.5.1.1.2		**ODUT trail termination sink function (ODUT_TT_Sk)**
pN_delay <-- nN_delay (Ʃ number of frames between the DMValue toggle event and the received DMp signal value toggle event)

**Comment by amazzini** [comment]
ODU FM & PM enhancements #454 introduces the pN_delay counter. Still to be agreed the removal of dmSource and dmValue.

**Comment by amazzini** [comment]
This issue has been closed due to the lack of activity for more than one year.
Please reopen it if follow up is necessary.
