### ISSUE TITLE
ODU topology in reference implementation fails when requesting topology-context

### ISSUE THREAD

**Issue by preetjuniper** [Open-Network-Models-and-Interfaces-ONMI/TAPI#451]
Hi,

After running the reference implementation server, I issue a GET to `http://$ip:8081//localhost:1234/data/context/topology-context/` but the response is empty (the response code is 200 OK). If I try `http://$ip:8081//localhost:1234/data/context`, I get the expected response. As the commit comment for https://github.com/OpenNetworkingFoundation/TAPI/commit/88a8af56a6376d6ebf4dcd50d731a88fe910caba mentions, this is probably due to a T-API version change. Can the topology be updated to conform to T-API 2.1/2.2?

**Comment by amazzini** [comment]
This issue has been closed due to the lack of activity for more than one year.
Please reopen it if follow up is necessary.
