### ISSUE TITLE
Issues with tapi-streaming@2017-11-13.yang

### ISSUE THREAD

**Issue by jmacauley** [Open-Network-Models-and-Interfaces-ONMI/TAPI#461]
Trying to compile the TAPI YANG files with ygot for use with golang.  Running into a number of issues with tapi-streaming@2017-11-13.yang.  I know these are generated from UML but I will point out the YANG issues.

1. line 747 contains "type tapi-notification:source-indicator;" but "tapi-notification" is never imported.  Not sure if an import is required, or the duplicate "source-indicator" structure on line 440 was the target?

2. Line 651 and 676 "supported-sream-type" should be "supported-stream-type".

3. Line 37, 44, and 51 define augment elements that are not valid paths.  There is no "stream-record" as a child element of "available-stream".  Not sure what was intended.

4. Line 37 defines an augment element augmenting "condition-detector" which is not a valid child element of "log-record-body".  Perhaps "condition-detector-record"?

**Comment by amazzini** [comment]
This issue has been closed due to the lack of activity for more than one year.
Please reopen it if follow up is necessary.
