### ISSUE TITLE
running yang2swag.sh fails

### ISSUE THREAD

**Issue by damianoneill** [Open-Network-Models-and-Interfaces-ONMI/TAPI#485]
When running the script it expects another project to be checkout out at ../EAGLE with the folder ../EAGLE/YangJsonTools 

Looking through the OpenNetworkFoundation group on GitHub shows the following projects 

https://github.com/OpenNetworkingFoundation?q=EAGLE&type=&language=

- EagleUmlCommon
- EagleUmlYang
- EagleYangUml
- EagleYangOpenApi
- EagleUmlOpenAPI

None of these contains a folder called YangJsonTools, can you provide a pointer to this folder?

```console
$ sh yang2swag.sh
Generating SWAGGER files from YANG files
Generating tapi-oam@2019-03-31.json from ./YANG//tapi-oam@2019-03-31.yang
Usage: pyang [options] [<filename>...]

Validates the YANG module in <filename> (or stdin), and all its dependencies.

pyang: error: no such option: --generate-rpc
Generating tapi-equipment@2019-03-31.json from ./YANG//tapi-equipment@2019-03-31.yang
Usage: pyang [options] [<filename>...]

```

**Comment by amazzini** [comment]
This issue has been closed due to the lack of activity for more than one year.
Please reopen it if follow up is necessary.
