### ISSUE TITLE
How to send a notification of a local object changed?

### ISSUE THREAD

**Issue by Moneyj0408150** [Open-Network-Models-and-Interfaces-ONMI/TAPI#491]
The "target-object" included in notification can only be global object, as target-object-identifier can only be the type of  uuid. While some local objects, such as ROUTE, SWITCH, should be notified when changed or generated according to TR 547. It is confused how to notify them by the notification defined in TAPI v2.1.3.

**Comment by amazzini** [comment]
This aspect has been clarified in TR-547 v1.1
