### ISSUE TITLE
OAS Swaager is not RESTCONF

### ISSUE THREAD

**Issue by rgaglian** [Open-Network-Models-and-Interfaces-ONMI/TAPI#494]
I understand the OAS folder is not normative but what is the intend to publish it if it does not follow RFC8040RFC7951? The root cause are bugs in the Yang2Swagger tool and how it was used to create these Swagger files. I would recommend removing the OAS folder.

**Comment by rgaglian** [comment]
I can see that OAS folder is still present in future r2.3 release for TAPI. Again, if we are publishing something that we know is wrong to our own specifications, sounds like a very bad idea.

**Comment by amazzini** [comment]
This issue has been closed due to the lack of activity for more than one year.
Please reopen it if follow up is necessary.
