### ISSUE TITLE
tapi-dsr: missing Fiber Channel rate 10GFC

### ISSUE THREAD

**Issue by pkostuch** [Open-Network-Models-and-Interfaces-ONMI/TAPI#506]
Hello, I think the tapi-dsr.yang does not include 10GFC. Is it possible to include 10GFC?

EDIT: Is 10GFC represented as FC1200? DIGITAL_SIGNAL_TYPE_FC_1200

**Comment by amazzini** [comment]
This issue has been closed due to the lack of activity for more than one year.
Please reopen it if follow up is necessary.
