### ISSUE TITLE
Some doubts about OAM-related concepts

### ISSUE THREAD

**Issue by aishouyi** [Open-Network-Models-and-Interfaces-ONMI/TAPI#551]
How is TAPI OAM implemented at the DSR, ODU, and PhotoshopNIC_Media layers? What are the concepts of TAPI OAMService and OAMServicePoint corresponding to TAPI OAM?

**Comment by roshan-joyce-fujitsu** [comment]
@aishouyi ,
Please see if some of the Q&A in the contribution https://wiki.opennetworking.org/download/attachments/259719184/TAPI-OAM-Questions-v1-am.xlsx?api=v2 brings more clarity.

**Comment by aishouyi** [comment]
> @aishouyi , Please see if some of the Q&A in the contribution https://wiki.opennetworking.org/download/attachments/259719184/TAPI-OAM-Questions-v1-am.xlsx?api=v2 brings more clarity.

thanks
